<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
// Credentials depending on environment
$credentials = array(

    'local' => array(
        'hostname' => 'localhost',
        'username' => 'root',
        'password' => 'masonic',
        'database' => 'thuoctau',
        'port' => 3306,
    ),

    'staging' => array(
        'hostname' => 'localhost',
        'username' => 'user',
        'password' => 'password',
        'database' => 'database',
        'port' => 3306,
    ),

);

$current = $credentials['local'];

if(isset($_SERVER) && array_key_exists('HTTP_HOST', $_SERVER))
{
    $currentDomain = $_SERVER['HTTP_HOST'];

    if(in_array($currentDomain, ['thuoctau.com.vn', 'thuoctau.50webs.com']))
    {
        $current = $credentials['staging'];
    }
}

// Native CodeIgniter functionality
$active_group = 'default';
$active_record = TRUE;

global $db;

$db['default']['hostname'] = $current['hostname'];
$db['default']['username'] = $current['username'];
$db['default']['password'] = $current['password'];
$db['default']['database'] = $current['database'];
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = '';
$db['default']['swap_pre'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_unicode_ci';
$db['default']['port'] = $current['port'];
/* End of file database.php */
/* Auto generated by Installer on 2011.06.08 12:42:31 */
/* Location: ./application/config/database.php */
