<?php
/**
 * Created by PhpStorm.
 * User: rueta
 * Date: 4/28/15
 * Time: 6:19 AM
 */
namespace Ionize\CLI\Services;

use Illuminate\Container\Container;
use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;


class DatabaseCapsule extends Capsule {


    public function __construct($credentials=[], Container $container = null)
    {
        parent::__construct($container); // TODO: Change the autogenerated stub

        $this->addConnection([
            'driver'    => 'mysql',
            'host'      => $credentials['hostname'],
            'database'  => $credentials['database'],
            'username'  => $credentials['username'],
            'password'  => $credentials['password'],
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ]);

        // Set the event dispatcher used by Eloquent models... (optional)
        $this->setEventDispatcher(new Dispatcher(new Container));

        // Make this Capsule instance available globally via static methods... (optional)
        $this->setAsGlobal();

        // Setup the Eloquent ORM... (optional; unless you've used setEventDispatcher())
        $this->bootEloquent();
    }


}